/*
 * MessagePack for C++ version switcher
 *
 * Copyright (C) 2014 KONDO Takatoshi
 *
 *    Distributed under the Boost Software License, Version 1.0.
 *    (See accompanying file LICENSE_1_0.txt or copy at
 *    http://www.boost.org/LICENSE_1_0.txt)
 */
#ifndef MSGHANDLE_VERSIONING_HPP
#define MSGHANDLE_VERSIONING_HPP

#include "msghandle/cpp_version.hpp"

#if !defined(MSGHANDLE_DEFAULT_API_VERSION)
#define MSGHANDLE_DEFAULT_API_VERSION 3
#endif

#define MSGHANDLE_DEFAULT_API_NS MSGHANDLE_DETAIL_PP_CAT(v, MSGHANDLE_DEFAULT_API_VERSION)

#if   MSGHANDLE_DEFAULT_API_VERSION == 1
#define MSGHANDLE_DETAIL_PP_ENABLE_NS_v1 ()
#elif MSGHANDLE_DEFAULT_API_VERSION == 2
#define MSGHANDLE_DETAIL_PP_ENABLE_NS_v2 ()
#elif MSGHANDLE_DEFAULT_API_VERSION == 3
#define MSGHANDLE_DETAIL_PP_ENABLE_NS_v3 ()
#else
#error
#endif

#define MSGHANDLE_DETAIL_PP_CAT(a, ...) MSGHANDLE_DETAIL_PP_PRIMITIVE_CAT(a, __VA_ARGS__)
#define MSGHANDLE_DETAIL_PP_PRIMITIVE_CAT(a, ...) a ## __VA_ARGS__

#define MSGHANDLE_DETAIL_PP_IIF(c) MSGHANDLE_DETAIL_PP_PRIMITIVE_CAT(MSGHANDLE_DETAIL_PP_IIF_, c)
#define MSGHANDLE_DETAIL_PP_IIF_0(t, ...) __VA_ARGS__
#define MSGHANDLE_DETAIL_PP_IIF_1(t, ...) t

#define MSGHANDLE_DETAIL_PP_PROBE(x) x, 1

#if defined(_MSC_VER)

#define MSGHANDLE_DETAIL_PP_MSVC_VA_ARGS_WORKAROUND(define, args) define args
#define MSGHANDLE_DETAIL_PP_CHECK(...) MSGHANDLE_DETAIL_PP_MSVC_VA_ARGS_WORKAROUND(MSGHANDLE_DETAIL_PP_CHECK_N, (__VA_ARGS__, 0))
#define MSGHANDLE_DETAIL_PP_CHECK_N(x, n, ...) n

#else  // defined(__MSC_VER)

#define MSGHANDLE_DETAIL_PP_CHECK(...) MSGHANDLE_DETAIL_PP_CHECK_N(__VA_ARGS__, 0)
#define MSGHANDLE_DETAIL_PP_CHECK_N(x, n, ...) n

#endif // defined(__MSC_VER)


#define MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE(ns)            MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_PROXY( MSGHANDLE_DETAIL_PP_ENABLE_NS_##ns )
#define MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_PROXY(...)     MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_PRIMIVIE(__VA_ARGS__)
#define MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_PRIMIVIE(x)    MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_COMBINE_ x
#define MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE_COMBINE_(...)  MSGHANDLE_DETAIL_PP_PROBE(~)

#define MSGHANDLE_DETAIL_PP_IS_NS_ENABLED(ns) MSGHANDLE_DETAIL_PP_CHECK(MSGHANDLE_DETAIL_PP_NS_ENABLED_PROBE(ns))

#ifdef MSGHANDLE_USE_CPP03
#define MSGHANDLE_API_VERSION_NAMESPACE(ns) MSGHANDLE_DETAIL_PP_IIF(MSGHANDLE_DETAIL_PP_IS_NS_ENABLED(ns)) \
    (namespace ns{}; using namespace ns; namespace ns, \
     namespace ns)

#else  // MSGHANDLE_USE_CPP03

#define MSGHANDLE_API_VERSION_NAMESPACE(ns) MSGHANDLE_DETAIL_PP_IIF(MSGHANDLE_DETAIL_PP_IS_NS_ENABLED(ns)) \
    (inline namespace ns, namespace ns)

#endif // MSGHANDLE_USE_CPP03

#endif // MSGHANDLE_VERSIONING_HPP
