# /* Copyright (C) 2001
#  * Housemarque Oy
#  * http://www.housemarque.com
#  *
#  * Distributed under the Boost Software License, Version 1.0. (See
#  * accompanying file LICENSE_1_0.txt or copy at
#  * http://www.boost.org/LICENSE_1_0.txt)
#  */
#
# /* Revised by Paul Mensonides (2002) */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef MSGHANDLE_PREPROCESSOR_LIST_FOR_EACH_PRODUCT_HPP
# define MSGHANDLE_PREPROCESSOR_LIST_FOR_EACH_PRODUCT_HPP
#
# include <msghandle/preprocessor/config/config.hpp>
# include <msghandle/preprocessor/control/if.hpp>
# include <msghandle/preprocessor/list/adt.hpp>
# include <msghandle/preprocessor/list/to_tuple.hpp>
# include <msghandle/preprocessor/repetition/for.hpp>
# include <msghandle/preprocessor/tuple/elem.hpp>
# include <msghandle/preprocessor/tuple/to_list.hpp>
# include <msghandle/preprocessor/tuple/rem.hpp>
# include <msghandle/preprocessor/tuple/reverse.hpp>
#
# /* MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT */
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_EDG()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT(macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(MSGHANDLE_PP_FOR, macro, size, MSGHANDLE_PP_TUPLE_TO_LIST(size, tuple))
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT(macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_Q(macro, size, tuple)
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_Q(macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(MSGHANDLE_PP_FOR, macro, size, MSGHANDLE_PP_TUPLE_TO_LIST(size, tuple))
# endif
#
# /* MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_R */
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_EDG()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_R(r, macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(MSGHANDLE_PP_FOR_ ## r, macro, size, MSGHANDLE_PP_TUPLE_TO_LIST(size, tuple))
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_R(r, macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_R_Q(r, macro, size, tuple)
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_R_Q(r, macro, size, tuple) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(MSGHANDLE_PP_FOR_ ## r, macro, size, MSGHANDLE_PP_TUPLE_TO_LIST(size, tuple))
# endif
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_EDG()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(impl, macro, size, lists) impl((MSGHANDLE_PP_LIST_FIRST(lists), MSGHANDLE_PP_LIST_REST(lists), MSGHANDLE_PP_NIL, macro, size), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_0)
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E(impl, macro, size, lists) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E_D(impl, macro, size, lists)
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_E_D(impl, macro, size, lists) impl((MSGHANDLE_PP_LIST_FIRST(lists), MSGHANDLE_PP_LIST_REST(lists), MSGHANDLE_PP_NIL, macro, size), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_0)
# endif
#
# if MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_STRICT()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P_I data
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P_I(a, b, res, macro, size) MSGHANDLE_PP_LIST_IS_CONS(a)
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P(r, data) MSGHANDLE_PP_LIST_IS_CONS(MSGHANDLE_PP_TUPLE_ELEM(5, 0, data))
# endif
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_MWCC()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O_I data
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O_I(a, b, res, macro, size) (MSGHANDLE_PP_LIST_REST(a), b, res, macro, size)
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O(r, data) (MSGHANDLE_PP_LIST_REST(MSGHANDLE_PP_TUPLE_ELEM(5, 0, data)), MSGHANDLE_PP_TUPLE_ELEM(5, 1, data), MSGHANDLE_PP_TUPLE_ELEM(5, 2, data), MSGHANDLE_PP_TUPLE_ELEM(5, 3, data), MSGHANDLE_PP_TUPLE_ELEM(5, 4, data))
# endif
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_EDG()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_I(r, MSGHANDLE_PP_TUPLE_ELEM(5, 0, data), MSGHANDLE_PP_TUPLE_ELEM(5, 1, data), MSGHANDLE_PP_TUPLE_ELEM(5, 2, data), MSGHANDLE_PP_TUPLE_ELEM(5, 3, data), MSGHANDLE_PP_TUPLE_ELEM(5, 4, data))
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_D(r, MSGHANDLE_PP_TUPLE_REM_5 data)
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_D(r, data_e) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_I(r, data_e)
# endif
#
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_I(r, a, b, res, macro, size) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_II(r, macro, MSGHANDLE_PP_LIST_TO_TUPLE_R(r, (MSGHANDLE_PP_LIST_FIRST(a), res)), size)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_II(r, macro, args, size) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_III(r, macro, args, size)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I_III(r, macro, args, size) macro(r, MSGHANDLE_PP_TUPLE_REVERSE(size, args))
#
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, i) MSGHANDLE_PP_IF(MSGHANDLE_PP_LIST_IS_CONS(MSGHANDLE_PP_TUPLE_ELEM(5, 1, data)), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_ ## i, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_I)
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_MWCC()
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H_I data
# else
#    define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H_I(MSGHANDLE_PP_TUPLE_ELEM(5, 0, data), MSGHANDLE_PP_TUPLE_ELEM(5, 1, data), MSGHANDLE_PP_TUPLE_ELEM(5, 2, data), MSGHANDLE_PP_TUPLE_ELEM(5, 3, data), MSGHANDLE_PP_TUPLE_ELEM(5, 4, data))
# endif
#
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H_I(a, b, res, macro, size) (MSGHANDLE_PP_LIST_FIRST(b), MSGHANDLE_PP_LIST_REST(b), (MSGHANDLE_PP_LIST_FIRST(a), res), macro, size)
#
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_0(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_1(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_2(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_3(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_4(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_5(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_6(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_7(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_8(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_9(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_10(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_11(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_12(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_13(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_14(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_15(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_16(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_17(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_18(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_19(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_20(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_21(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_22(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_23(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_24(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_25(r, data) MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_0(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_1)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_1(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_2)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_2(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_3)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_3(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_4)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_4(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_5)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_5(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_6)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_6(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_7)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_7(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_8)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_8(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_9)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_9(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_10)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_10(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_11)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_11(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_12)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_12(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_13)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_13(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_14)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_14(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_15)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_15(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_16)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_16(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_17)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_17(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_18)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_18(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_19)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_19(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_20)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_20(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_21)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_21(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_22)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_22(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_23)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_23(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_24)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_24(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_25)
# define MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_N_25(r, data) MSGHANDLE_PP_FOR_ ## r(MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_H(data), MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_P, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_O, MSGHANDLE_PP_LIST_FOR_EACH_PRODUCT_M_26)
#
# endif
