# config.yaml
topics:
  - "/tpvehiclestate"
  - "/tpimu"
  - "/tpappremotecmd"
  - "/tplocalization"
  - "/tpbusiness_cmd"
  - "/tppathplan"
  - "/tpvehicle_to_can"
  - "/tpvehicle_to_can_rc"
  - "/tpplanningstatus_rc"
  - "/tpplanningstatus"
  - "/tpsemanticmap"
  - "/tpperceptionobjects"
  - "/tpleftboundary"
  - "/tprightboundary"
  - "/tppathdebug"
  - "/tpperception_objs"
  - "/tppathplan_path_following"
  - "/tppathplan_person_following"
  - "/video_profile"
  - "/video_parameter"
  - "packets"
  - "/perception/vpresult"
  - "target_obj"
  - "compressed_image_list"
split_time: 60
output: "/aabag/"
is_recordbycmd: false
cmd_topic: "/cmd"
cmd_type: "cmdtype"
