Camera:/HuaweiMDC/PlatformApplication/CameraAppApplication/CameraAppSwComponent/CameraAppApplicationSwComponent
Lidar:/HuaweiMDC/PlatformApplication/LidarCmCenterApplication/SwComponent/liblidar_a_cm
Radar:/HuaweiMDC/PlatformApplication/RadarCenterApplication/SwComponent/radar_a_cm
Uss:/HuaweiMDC/PlatformApplication/UssCmCenterApplication/SwComponent/libuss_a_cm
INS:/HuaweiMDC/PlatformApplication/InsCmCenterApplication/SwComponent/ins_a_cm
Body:/HuaweiMDC/PlatformApplication/BodyCenterApplication/SwComponent/libbody_a_cm
Chassis:/HuaweiMDC/PlatformApplication/ChassisCenterApplication/SwComponent/libchassis_a_cm

FaultManager:/HuaweiMDC/PlatformApplication/FmApplication/SwcComponent/fm