#ifndef SRC_EXECUTION_REFPATH_UNSTRUCT_REFPATH_INCLUDE_UNSTRUCT_REFPATH_DEFINE_H_
#define SRC_EXECUTION_REFPATH_UNSTRUCT_REFPATH_INCLUDE_UNSTRUCT_REFPATH_DEFINE_H_

namespace avos{
namespace planning {

#define UNST_INIT_PATH_EMPTY          0
#define UNST_RAW_ECTRACTION_RAW_EMPTY 1
#define UNST_GET_PATH_LOCAL_EMPTY 2
#define UNST_GET_PATH_LOCAL_INDEX_OUTOF_BOUNDARY 3
#define UNST_GET_PATH_LOCAL_INDEX_ERROR 4
#define UNST_LOCALIZATION_ERROR 5
#define UNST_EDITPATH_EMPTY_ERROR 6
#define UNST_EDITPATH_INDEX_ERROR 7
#define UNST_EDITPATH_DIS_ERROR 8



} // namespace planning
} // namespace avos


#endif
