# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef MSGHANDLE_PREPROCESSOR_SEQ_ELEM_HPP
# define MSGHANDLE_PREPROCESSOR_SEQ_ELEM_HPP
#
# include <msghandle/preprocessor/cat.hpp>
# include <msghandle/preprocessor/config/config.hpp>
# include <msghandle/preprocessor/facilities/empty.hpp>
#
# /* MSGHANDLE_PP_SEQ_ELEM */
#
# if ~MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_MWCC()
#    define MSGHANDLE_PP_SEQ_ELEM(i, seq) MSGHANDLE_PP_SEQ_ELEM_I(i, seq)
# else
#    define MSGHANDLE_PP_SEQ_ELEM(i, seq) MSGHANDLE_PP_SEQ_ELEM_I((i, seq))
# endif
#
# if MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_MSVC()
#    define MSGHANDLE_PP_SEQ_ELEM_I(i, seq) MSGHANDLE_PP_SEQ_ELEM_II((MSGHANDLE_PP_SEQ_ELEM_ ## i seq))
#    define MSGHANDLE_PP_SEQ_ELEM_II(res) MSGHANDLE_PP_SEQ_ELEM_IV(MSGHANDLE_PP_SEQ_ELEM_III res)
#    define MSGHANDLE_PP_SEQ_ELEM_III(x, _) x MSGHANDLE_PP_EMPTY()
#    define MSGHANDLE_PP_SEQ_ELEM_IV(x) x
# elif MSGHANDLE_PP_CONFIG_FLAGS() & MSGHANDLE_PP_CONFIG_MWCC()
#    define MSGHANDLE_PP_SEQ_ELEM_I(par) MSGHANDLE_PP_SEQ_ELEM_II ## par
#    define MSGHANDLE_PP_SEQ_ELEM_II(i, seq) MSGHANDLE_PP_SEQ_ELEM_III(MSGHANDLE_PP_SEQ_ELEM_ ## i ## seq)
#    define MSGHANDLE_PP_SEQ_ELEM_III(im) MSGHANDLE_PP_SEQ_ELEM_IV(im)
#    define MSGHANDLE_PP_SEQ_ELEM_IV(x, _) x
# else
#    if defined(__IBMC__) || defined(__IBMCPP__)
#        define MSGHANDLE_PP_SEQ_ELEM_I(i, seq) MSGHANDLE_PP_SEQ_ELEM_II(MSGHANDLE_PP_CAT(MSGHANDLE_PP_SEQ_ELEM_ ## i, seq))
#    else
#        define MSGHANDLE_PP_SEQ_ELEM_I(i, seq) MSGHANDLE_PP_SEQ_ELEM_II(MSGHANDLE_PP_SEQ_ELEM_ ## i seq)
#    endif
#    define MSGHANDLE_PP_SEQ_ELEM_II(im) MSGHANDLE_PP_SEQ_ELEM_III(im)
#    define MSGHANDLE_PP_SEQ_ELEM_III(x, _) x
# endif
#
# define MSGHANDLE_PP_SEQ_ELEM_0(x) x, MSGHANDLE_PP_NIL
# define MSGHANDLE_PP_SEQ_ELEM_1(_) MSGHANDLE_PP_SEQ_ELEM_0
# define MSGHANDLE_PP_SEQ_ELEM_2(_) MSGHANDLE_PP_SEQ_ELEM_1
# define MSGHANDLE_PP_SEQ_ELEM_3(_) MSGHANDLE_PP_SEQ_ELEM_2
# define MSGHANDLE_PP_SEQ_ELEM_4(_) MSGHANDLE_PP_SEQ_ELEM_3
# define MSGHANDLE_PP_SEQ_ELEM_5(_) MSGHANDLE_PP_SEQ_ELEM_4
# define MSGHANDLE_PP_SEQ_ELEM_6(_) MSGHANDLE_PP_SEQ_ELEM_5
# define MSGHANDLE_PP_SEQ_ELEM_7(_) MSGHANDLE_PP_SEQ_ELEM_6
# define MSGHANDLE_PP_SEQ_ELEM_8(_) MSGHANDLE_PP_SEQ_ELEM_7
# define MSGHANDLE_PP_SEQ_ELEM_9(_) MSGHANDLE_PP_SEQ_ELEM_8
# define MSGHANDLE_PP_SEQ_ELEM_10(_) MSGHANDLE_PP_SEQ_ELEM_9
# define MSGHANDLE_PP_SEQ_ELEM_11(_) MSGHANDLE_PP_SEQ_ELEM_10
# define MSGHANDLE_PP_SEQ_ELEM_12(_) MSGHANDLE_PP_SEQ_ELEM_11
# define MSGHANDLE_PP_SEQ_ELEM_13(_) MSGHANDLE_PP_SEQ_ELEM_12
# define MSGHANDLE_PP_SEQ_ELEM_14(_) MSGHANDLE_PP_SEQ_ELEM_13
# define MSGHANDLE_PP_SEQ_ELEM_15(_) MSGHANDLE_PP_SEQ_ELEM_14
# define MSGHANDLE_PP_SEQ_ELEM_16(_) MSGHANDLE_PP_SEQ_ELEM_15
# define MSGHANDLE_PP_SEQ_ELEM_17(_) MSGHANDLE_PP_SEQ_ELEM_16
# define MSGHANDLE_PP_SEQ_ELEM_18(_) MSGHANDLE_PP_SEQ_ELEM_17
# define MSGHANDLE_PP_SEQ_ELEM_19(_) MSGHANDLE_PP_SEQ_ELEM_18
# define MSGHANDLE_PP_SEQ_ELEM_20(_) MSGHANDLE_PP_SEQ_ELEM_19
# define MSGHANDLE_PP_SEQ_ELEM_21(_) MSGHANDLE_PP_SEQ_ELEM_20
# define MSGHANDLE_PP_SEQ_ELEM_22(_) MSGHANDLE_PP_SEQ_ELEM_21
# define MSGHANDLE_PP_SEQ_ELEM_23(_) MSGHANDLE_PP_SEQ_ELEM_22
# define MSGHANDLE_PP_SEQ_ELEM_24(_) MSGHANDLE_PP_SEQ_ELEM_23
# define MSGHANDLE_PP_SEQ_ELEM_25(_) MSGHANDLE_PP_SEQ_ELEM_24
# define MSGHANDLE_PP_SEQ_ELEM_26(_) MSGHANDLE_PP_SEQ_ELEM_25
# define MSGHANDLE_PP_SEQ_ELEM_27(_) MSGHANDLE_PP_SEQ_ELEM_26
# define MSGHANDLE_PP_SEQ_ELEM_28(_) MSGHANDLE_PP_SEQ_ELEM_27
# define MSGHANDLE_PP_SEQ_ELEM_29(_) MSGHANDLE_PP_SEQ_ELEM_28
# define MSGHANDLE_PP_SEQ_ELEM_30(_) MSGHANDLE_PP_SEQ_ELEM_29
# define MSGHANDLE_PP_SEQ_ELEM_31(_) MSGHANDLE_PP_SEQ_ELEM_30
# define MSGHANDLE_PP_SEQ_ELEM_32(_) MSGHANDLE_PP_SEQ_ELEM_31
# define MSGHANDLE_PP_SEQ_ELEM_33(_) MSGHANDLE_PP_SEQ_ELEM_32
# define MSGHANDLE_PP_SEQ_ELEM_34(_) MSGHANDLE_PP_SEQ_ELEM_33
# define MSGHANDLE_PP_SEQ_ELEM_35(_) MSGHANDLE_PP_SEQ_ELEM_34
# define MSGHANDLE_PP_SEQ_ELEM_36(_) MSGHANDLE_PP_SEQ_ELEM_35
# define MSGHANDLE_PP_SEQ_ELEM_37(_) MSGHANDLE_PP_SEQ_ELEM_36
# define MSGHANDLE_PP_SEQ_ELEM_38(_) MSGHANDLE_PP_SEQ_ELEM_37
# define MSGHANDLE_PP_SEQ_ELEM_39(_) MSGHANDLE_PP_SEQ_ELEM_38
# define MSGHANDLE_PP_SEQ_ELEM_40(_) MSGHANDLE_PP_SEQ_ELEM_39
# define MSGHANDLE_PP_SEQ_ELEM_41(_) MSGHANDLE_PP_SEQ_ELEM_40
# define MSGHANDLE_PP_SEQ_ELEM_42(_) MSGHANDLE_PP_SEQ_ELEM_41
# define MSGHANDLE_PP_SEQ_ELEM_43(_) MSGHANDLE_PP_SEQ_ELEM_42
# define MSGHANDLE_PP_SEQ_ELEM_44(_) MSGHANDLE_PP_SEQ_ELEM_43
# define MSGHANDLE_PP_SEQ_ELEM_45(_) MSGHANDLE_PP_SEQ_ELEM_44
# define MSGHANDLE_PP_SEQ_ELEM_46(_) MSGHANDLE_PP_SEQ_ELEM_45
# define MSGHANDLE_PP_SEQ_ELEM_47(_) MSGHANDLE_PP_SEQ_ELEM_46
# define MSGHANDLE_PP_SEQ_ELEM_48(_) MSGHANDLE_PP_SEQ_ELEM_47
# define MSGHANDLE_PP_SEQ_ELEM_49(_) MSGHANDLE_PP_SEQ_ELEM_48
# define MSGHANDLE_PP_SEQ_ELEM_50(_) MSGHANDLE_PP_SEQ_ELEM_49
# define MSGHANDLE_PP_SEQ_ELEM_51(_) MSGHANDLE_PP_SEQ_ELEM_50
# define MSGHANDLE_PP_SEQ_ELEM_52(_) MSGHANDLE_PP_SEQ_ELEM_51
# define MSGHANDLE_PP_SEQ_ELEM_53(_) MSGHANDLE_PP_SEQ_ELEM_52
# define MSGHANDLE_PP_SEQ_ELEM_54(_) MSGHANDLE_PP_SEQ_ELEM_53
# define MSGHANDLE_PP_SEQ_ELEM_55(_) MSGHANDLE_PP_SEQ_ELEM_54
# define MSGHANDLE_PP_SEQ_ELEM_56(_) MSGHANDLE_PP_SEQ_ELEM_55
# define MSGHANDLE_PP_SEQ_ELEM_57(_) MSGHANDLE_PP_SEQ_ELEM_56
# define MSGHANDLE_PP_SEQ_ELEM_58(_) MSGHANDLE_PP_SEQ_ELEM_57
# define MSGHANDLE_PP_SEQ_ELEM_59(_) MSGHANDLE_PP_SEQ_ELEM_58
# define MSGHANDLE_PP_SEQ_ELEM_60(_) MSGHANDLE_PP_SEQ_ELEM_59
# define MSGHANDLE_PP_SEQ_ELEM_61(_) MSGHANDLE_PP_SEQ_ELEM_60
# define MSGHANDLE_PP_SEQ_ELEM_62(_) MSGHANDLE_PP_SEQ_ELEM_61
# define MSGHANDLE_PP_SEQ_ELEM_63(_) MSGHANDLE_PP_SEQ_ELEM_62
# define MSGHANDLE_PP_SEQ_ELEM_64(_) MSGHANDLE_PP_SEQ_ELEM_63
# define MSGHANDLE_PP_SEQ_ELEM_65(_) MSGHANDLE_PP_SEQ_ELEM_64
# define MSGHANDLE_PP_SEQ_ELEM_66(_) MSGHANDLE_PP_SEQ_ELEM_65
# define MSGHANDLE_PP_SEQ_ELEM_67(_) MSGHANDLE_PP_SEQ_ELEM_66
# define MSGHANDLE_PP_SEQ_ELEM_68(_) MSGHANDLE_PP_SEQ_ELEM_67
# define MSGHANDLE_PP_SEQ_ELEM_69(_) MSGHANDLE_PP_SEQ_ELEM_68
# define MSGHANDLE_PP_SEQ_ELEM_70(_) MSGHANDLE_PP_SEQ_ELEM_69
# define MSGHANDLE_PP_SEQ_ELEM_71(_) MSGHANDLE_PP_SEQ_ELEM_70
# define MSGHANDLE_PP_SEQ_ELEM_72(_) MSGHANDLE_PP_SEQ_ELEM_71
# define MSGHANDLE_PP_SEQ_ELEM_73(_) MSGHANDLE_PP_SEQ_ELEM_72
# define MSGHANDLE_PP_SEQ_ELEM_74(_) MSGHANDLE_PP_SEQ_ELEM_73
# define MSGHANDLE_PP_SEQ_ELEM_75(_) MSGHANDLE_PP_SEQ_ELEM_74
# define MSGHANDLE_PP_SEQ_ELEM_76(_) MSGHANDLE_PP_SEQ_ELEM_75
# define MSGHANDLE_PP_SEQ_ELEM_77(_) MSGHANDLE_PP_SEQ_ELEM_76
# define MSGHANDLE_PP_SEQ_ELEM_78(_) MSGHANDLE_PP_SEQ_ELEM_77
# define MSGHANDLE_PP_SEQ_ELEM_79(_) MSGHANDLE_PP_SEQ_ELEM_78
# define MSGHANDLE_PP_SEQ_ELEM_80(_) MSGHANDLE_PP_SEQ_ELEM_79
# define MSGHANDLE_PP_SEQ_ELEM_81(_) MSGHANDLE_PP_SEQ_ELEM_80
# define MSGHANDLE_PP_SEQ_ELEM_82(_) MSGHANDLE_PP_SEQ_ELEM_81
# define MSGHANDLE_PP_SEQ_ELEM_83(_) MSGHANDLE_PP_SEQ_ELEM_82
# define MSGHANDLE_PP_SEQ_ELEM_84(_) MSGHANDLE_PP_SEQ_ELEM_83
# define MSGHANDLE_PP_SEQ_ELEM_85(_) MSGHANDLE_PP_SEQ_ELEM_84
# define MSGHANDLE_PP_SEQ_ELEM_86(_) MSGHANDLE_PP_SEQ_ELEM_85
# define MSGHANDLE_PP_SEQ_ELEM_87(_) MSGHANDLE_PP_SEQ_ELEM_86
# define MSGHANDLE_PP_SEQ_ELEM_88(_) MSGHANDLE_PP_SEQ_ELEM_87
# define MSGHANDLE_PP_SEQ_ELEM_89(_) MSGHANDLE_PP_SEQ_ELEM_88
# define MSGHANDLE_PP_SEQ_ELEM_90(_) MSGHANDLE_PP_SEQ_ELEM_89
# define MSGHANDLE_PP_SEQ_ELEM_91(_) MSGHANDLE_PP_SEQ_ELEM_90
# define MSGHANDLE_PP_SEQ_ELEM_92(_) MSGHANDLE_PP_SEQ_ELEM_91
# define MSGHANDLE_PP_SEQ_ELEM_93(_) MSGHANDLE_PP_SEQ_ELEM_92
# define MSGHANDLE_PP_SEQ_ELEM_94(_) MSGHANDLE_PP_SEQ_ELEM_93
# define MSGHANDLE_PP_SEQ_ELEM_95(_) MSGHANDLE_PP_SEQ_ELEM_94
# define MSGHANDLE_PP_SEQ_ELEM_96(_) MSGHANDLE_PP_SEQ_ELEM_95
# define MSGHANDLE_PP_SEQ_ELEM_97(_) MSGHANDLE_PP_SEQ_ELEM_96
# define MSGHANDLE_PP_SEQ_ELEM_98(_) MSGHANDLE_PP_SEQ_ELEM_97
# define MSGHANDLE_PP_SEQ_ELEM_99(_) MSGHANDLE_PP_SEQ_ELEM_98
# define MSGHANDLE_PP_SEQ_ELEM_100(_) MSGHANDLE_PP_SEQ_ELEM_99
# define MSGHANDLE_PP_SEQ_ELEM_101(_) MSGHANDLE_PP_SEQ_ELEM_100
# define MSGHANDLE_PP_SEQ_ELEM_102(_) MSGHANDLE_PP_SEQ_ELEM_101
# define MSGHANDLE_PP_SEQ_ELEM_103(_) MSGHANDLE_PP_SEQ_ELEM_102
# define MSGHANDLE_PP_SEQ_ELEM_104(_) MSGHANDLE_PP_SEQ_ELEM_103
# define MSGHANDLE_PP_SEQ_ELEM_105(_) MSGHANDLE_PP_SEQ_ELEM_104
# define MSGHANDLE_PP_SEQ_ELEM_106(_) MSGHANDLE_PP_SEQ_ELEM_105
# define MSGHANDLE_PP_SEQ_ELEM_107(_) MSGHANDLE_PP_SEQ_ELEM_106
# define MSGHANDLE_PP_SEQ_ELEM_108(_) MSGHANDLE_PP_SEQ_ELEM_107
# define MSGHANDLE_PP_SEQ_ELEM_109(_) MSGHANDLE_PP_SEQ_ELEM_108
# define MSGHANDLE_PP_SEQ_ELEM_110(_) MSGHANDLE_PP_SEQ_ELEM_109
# define MSGHANDLE_PP_SEQ_ELEM_111(_) MSGHANDLE_PP_SEQ_ELEM_110
# define MSGHANDLE_PP_SEQ_ELEM_112(_) MSGHANDLE_PP_SEQ_ELEM_111
# define MSGHANDLE_PP_SEQ_ELEM_113(_) MSGHANDLE_PP_SEQ_ELEM_112
# define MSGHANDLE_PP_SEQ_ELEM_114(_) MSGHANDLE_PP_SEQ_ELEM_113
# define MSGHANDLE_PP_SEQ_ELEM_115(_) MSGHANDLE_PP_SEQ_ELEM_114
# define MSGHANDLE_PP_SEQ_ELEM_116(_) MSGHANDLE_PP_SEQ_ELEM_115
# define MSGHANDLE_PP_SEQ_ELEM_117(_) MSGHANDLE_PP_SEQ_ELEM_116
# define MSGHANDLE_PP_SEQ_ELEM_118(_) MSGHANDLE_PP_SEQ_ELEM_117
# define MSGHANDLE_PP_SEQ_ELEM_119(_) MSGHANDLE_PP_SEQ_ELEM_118
# define MSGHANDLE_PP_SEQ_ELEM_120(_) MSGHANDLE_PP_SEQ_ELEM_119
# define MSGHANDLE_PP_SEQ_ELEM_121(_) MSGHANDLE_PP_SEQ_ELEM_120
# define MSGHANDLE_PP_SEQ_ELEM_122(_) MSGHANDLE_PP_SEQ_ELEM_121
# define MSGHANDLE_PP_SEQ_ELEM_123(_) MSGHANDLE_PP_SEQ_ELEM_122
# define MSGHANDLE_PP_SEQ_ELEM_124(_) MSGHANDLE_PP_SEQ_ELEM_123
# define MSGHANDLE_PP_SEQ_ELEM_125(_) MSGHANDLE_PP_SEQ_ELEM_124
# define MSGHANDLE_PP_SEQ_ELEM_126(_) MSGHANDLE_PP_SEQ_ELEM_125
# define MSGHANDLE_PP_SEQ_ELEM_127(_) MSGHANDLE_PP_SEQ_ELEM_126
# define MSGHANDLE_PP_SEQ_ELEM_128(_) MSGHANDLE_PP_SEQ_ELEM_127
# define MSGHANDLE_PP_SEQ_ELEM_129(_) MSGHANDLE_PP_SEQ_ELEM_128
# define MSGHANDLE_PP_SEQ_ELEM_130(_) MSGHANDLE_PP_SEQ_ELEM_129
# define MSGHANDLE_PP_SEQ_ELEM_131(_) MSGHANDLE_PP_SEQ_ELEM_130
# define MSGHANDLE_PP_SEQ_ELEM_132(_) MSGHANDLE_PP_SEQ_ELEM_131
# define MSGHANDLE_PP_SEQ_ELEM_133(_) MSGHANDLE_PP_SEQ_ELEM_132
# define MSGHANDLE_PP_SEQ_ELEM_134(_) MSGHANDLE_PP_SEQ_ELEM_133
# define MSGHANDLE_PP_SEQ_ELEM_135(_) MSGHANDLE_PP_SEQ_ELEM_134
# define MSGHANDLE_PP_SEQ_ELEM_136(_) MSGHANDLE_PP_SEQ_ELEM_135
# define MSGHANDLE_PP_SEQ_ELEM_137(_) MSGHANDLE_PP_SEQ_ELEM_136
# define MSGHANDLE_PP_SEQ_ELEM_138(_) MSGHANDLE_PP_SEQ_ELEM_137
# define MSGHANDLE_PP_SEQ_ELEM_139(_) MSGHANDLE_PP_SEQ_ELEM_138
# define MSGHANDLE_PP_SEQ_ELEM_140(_) MSGHANDLE_PP_SEQ_ELEM_139
# define MSGHANDLE_PP_SEQ_ELEM_141(_) MSGHANDLE_PP_SEQ_ELEM_140
# define MSGHANDLE_PP_SEQ_ELEM_142(_) MSGHANDLE_PP_SEQ_ELEM_141
# define MSGHANDLE_PP_SEQ_ELEM_143(_) MSGHANDLE_PP_SEQ_ELEM_142
# define MSGHANDLE_PP_SEQ_ELEM_144(_) MSGHANDLE_PP_SEQ_ELEM_143
# define MSGHANDLE_PP_SEQ_ELEM_145(_) MSGHANDLE_PP_SEQ_ELEM_144
# define MSGHANDLE_PP_SEQ_ELEM_146(_) MSGHANDLE_PP_SEQ_ELEM_145
# define MSGHANDLE_PP_SEQ_ELEM_147(_) MSGHANDLE_PP_SEQ_ELEM_146
# define MSGHANDLE_PP_SEQ_ELEM_148(_) MSGHANDLE_PP_SEQ_ELEM_147
# define MSGHANDLE_PP_SEQ_ELEM_149(_) MSGHANDLE_PP_SEQ_ELEM_148
# define MSGHANDLE_PP_SEQ_ELEM_150(_) MSGHANDLE_PP_SEQ_ELEM_149
# define MSGHANDLE_PP_SEQ_ELEM_151(_) MSGHANDLE_PP_SEQ_ELEM_150
# define MSGHANDLE_PP_SEQ_ELEM_152(_) MSGHANDLE_PP_SEQ_ELEM_151
# define MSGHANDLE_PP_SEQ_ELEM_153(_) MSGHANDLE_PP_SEQ_ELEM_152
# define MSGHANDLE_PP_SEQ_ELEM_154(_) MSGHANDLE_PP_SEQ_ELEM_153
# define MSGHANDLE_PP_SEQ_ELEM_155(_) MSGHANDLE_PP_SEQ_ELEM_154
# define MSGHANDLE_PP_SEQ_ELEM_156(_) MSGHANDLE_PP_SEQ_ELEM_155
# define MSGHANDLE_PP_SEQ_ELEM_157(_) MSGHANDLE_PP_SEQ_ELEM_156
# define MSGHANDLE_PP_SEQ_ELEM_158(_) MSGHANDLE_PP_SEQ_ELEM_157
# define MSGHANDLE_PP_SEQ_ELEM_159(_) MSGHANDLE_PP_SEQ_ELEM_158
# define MSGHANDLE_PP_SEQ_ELEM_160(_) MSGHANDLE_PP_SEQ_ELEM_159
# define MSGHANDLE_PP_SEQ_ELEM_161(_) MSGHANDLE_PP_SEQ_ELEM_160
# define MSGHANDLE_PP_SEQ_ELEM_162(_) MSGHANDLE_PP_SEQ_ELEM_161
# define MSGHANDLE_PP_SEQ_ELEM_163(_) MSGHANDLE_PP_SEQ_ELEM_162
# define MSGHANDLE_PP_SEQ_ELEM_164(_) MSGHANDLE_PP_SEQ_ELEM_163
# define MSGHANDLE_PP_SEQ_ELEM_165(_) MSGHANDLE_PP_SEQ_ELEM_164
# define MSGHANDLE_PP_SEQ_ELEM_166(_) MSGHANDLE_PP_SEQ_ELEM_165
# define MSGHANDLE_PP_SEQ_ELEM_167(_) MSGHANDLE_PP_SEQ_ELEM_166
# define MSGHANDLE_PP_SEQ_ELEM_168(_) MSGHANDLE_PP_SEQ_ELEM_167
# define MSGHANDLE_PP_SEQ_ELEM_169(_) MSGHANDLE_PP_SEQ_ELEM_168
# define MSGHANDLE_PP_SEQ_ELEM_170(_) MSGHANDLE_PP_SEQ_ELEM_169
# define MSGHANDLE_PP_SEQ_ELEM_171(_) MSGHANDLE_PP_SEQ_ELEM_170
# define MSGHANDLE_PP_SEQ_ELEM_172(_) MSGHANDLE_PP_SEQ_ELEM_171
# define MSGHANDLE_PP_SEQ_ELEM_173(_) MSGHANDLE_PP_SEQ_ELEM_172
# define MSGHANDLE_PP_SEQ_ELEM_174(_) MSGHANDLE_PP_SEQ_ELEM_173
# define MSGHANDLE_PP_SEQ_ELEM_175(_) MSGHANDLE_PP_SEQ_ELEM_174
# define MSGHANDLE_PP_SEQ_ELEM_176(_) MSGHANDLE_PP_SEQ_ELEM_175
# define MSGHANDLE_PP_SEQ_ELEM_177(_) MSGHANDLE_PP_SEQ_ELEM_176
# define MSGHANDLE_PP_SEQ_ELEM_178(_) MSGHANDLE_PP_SEQ_ELEM_177
# define MSGHANDLE_PP_SEQ_ELEM_179(_) MSGHANDLE_PP_SEQ_ELEM_178
# define MSGHANDLE_PP_SEQ_ELEM_180(_) MSGHANDLE_PP_SEQ_ELEM_179
# define MSGHANDLE_PP_SEQ_ELEM_181(_) MSGHANDLE_PP_SEQ_ELEM_180
# define MSGHANDLE_PP_SEQ_ELEM_182(_) MSGHANDLE_PP_SEQ_ELEM_181
# define MSGHANDLE_PP_SEQ_ELEM_183(_) MSGHANDLE_PP_SEQ_ELEM_182
# define MSGHANDLE_PP_SEQ_ELEM_184(_) MSGHANDLE_PP_SEQ_ELEM_183
# define MSGHANDLE_PP_SEQ_ELEM_185(_) MSGHANDLE_PP_SEQ_ELEM_184
# define MSGHANDLE_PP_SEQ_ELEM_186(_) MSGHANDLE_PP_SEQ_ELEM_185
# define MSGHANDLE_PP_SEQ_ELEM_187(_) MSGHANDLE_PP_SEQ_ELEM_186
# define MSGHANDLE_PP_SEQ_ELEM_188(_) MSGHANDLE_PP_SEQ_ELEM_187
# define MSGHANDLE_PP_SEQ_ELEM_189(_) MSGHANDLE_PP_SEQ_ELEM_188
# define MSGHANDLE_PP_SEQ_ELEM_190(_) MSGHANDLE_PP_SEQ_ELEM_189
# define MSGHANDLE_PP_SEQ_ELEM_191(_) MSGHANDLE_PP_SEQ_ELEM_190
# define MSGHANDLE_PP_SEQ_ELEM_192(_) MSGHANDLE_PP_SEQ_ELEM_191
# define MSGHANDLE_PP_SEQ_ELEM_193(_) MSGHANDLE_PP_SEQ_ELEM_192
# define MSGHANDLE_PP_SEQ_ELEM_194(_) MSGHANDLE_PP_SEQ_ELEM_193
# define MSGHANDLE_PP_SEQ_ELEM_195(_) MSGHANDLE_PP_SEQ_ELEM_194
# define MSGHANDLE_PP_SEQ_ELEM_196(_) MSGHANDLE_PP_SEQ_ELEM_195
# define MSGHANDLE_PP_SEQ_ELEM_197(_) MSGHANDLE_PP_SEQ_ELEM_196
# define MSGHANDLE_PP_SEQ_ELEM_198(_) MSGHANDLE_PP_SEQ_ELEM_197
# define MSGHANDLE_PP_SEQ_ELEM_199(_) MSGHANDLE_PP_SEQ_ELEM_198
# define MSGHANDLE_PP_SEQ_ELEM_200(_) MSGHANDLE_PP_SEQ_ELEM_199
# define MSGHANDLE_PP_SEQ_ELEM_201(_) MSGHANDLE_PP_SEQ_ELEM_200
# define MSGHANDLE_PP_SEQ_ELEM_202(_) MSGHANDLE_PP_SEQ_ELEM_201
# define MSGHANDLE_PP_SEQ_ELEM_203(_) MSGHANDLE_PP_SEQ_ELEM_202
# define MSGHANDLE_PP_SEQ_ELEM_204(_) MSGHANDLE_PP_SEQ_ELEM_203
# define MSGHANDLE_PP_SEQ_ELEM_205(_) MSGHANDLE_PP_SEQ_ELEM_204
# define MSGHANDLE_PP_SEQ_ELEM_206(_) MSGHANDLE_PP_SEQ_ELEM_205
# define MSGHANDLE_PP_SEQ_ELEM_207(_) MSGHANDLE_PP_SEQ_ELEM_206
# define MSGHANDLE_PP_SEQ_ELEM_208(_) MSGHANDLE_PP_SEQ_ELEM_207
# define MSGHANDLE_PP_SEQ_ELEM_209(_) MSGHANDLE_PP_SEQ_ELEM_208
# define MSGHANDLE_PP_SEQ_ELEM_210(_) MSGHANDLE_PP_SEQ_ELEM_209
# define MSGHANDLE_PP_SEQ_ELEM_211(_) MSGHANDLE_PP_SEQ_ELEM_210
# define MSGHANDLE_PP_SEQ_ELEM_212(_) MSGHANDLE_PP_SEQ_ELEM_211
# define MSGHANDLE_PP_SEQ_ELEM_213(_) MSGHANDLE_PP_SEQ_ELEM_212
# define MSGHANDLE_PP_SEQ_ELEM_214(_) MSGHANDLE_PP_SEQ_ELEM_213
# define MSGHANDLE_PP_SEQ_ELEM_215(_) MSGHANDLE_PP_SEQ_ELEM_214
# define MSGHANDLE_PP_SEQ_ELEM_216(_) MSGHANDLE_PP_SEQ_ELEM_215
# define MSGHANDLE_PP_SEQ_ELEM_217(_) MSGHANDLE_PP_SEQ_ELEM_216
# define MSGHANDLE_PP_SEQ_ELEM_218(_) MSGHANDLE_PP_SEQ_ELEM_217
# define MSGHANDLE_PP_SEQ_ELEM_219(_) MSGHANDLE_PP_SEQ_ELEM_218
# define MSGHANDLE_PP_SEQ_ELEM_220(_) MSGHANDLE_PP_SEQ_ELEM_219
# define MSGHANDLE_PP_SEQ_ELEM_221(_) MSGHANDLE_PP_SEQ_ELEM_220
# define MSGHANDLE_PP_SEQ_ELEM_222(_) MSGHANDLE_PP_SEQ_ELEM_221
# define MSGHANDLE_PP_SEQ_ELEM_223(_) MSGHANDLE_PP_SEQ_ELEM_222
# define MSGHANDLE_PP_SEQ_ELEM_224(_) MSGHANDLE_PP_SEQ_ELEM_223
# define MSGHANDLE_PP_SEQ_ELEM_225(_) MSGHANDLE_PP_SEQ_ELEM_224
# define MSGHANDLE_PP_SEQ_ELEM_226(_) MSGHANDLE_PP_SEQ_ELEM_225
# define MSGHANDLE_PP_SEQ_ELEM_227(_) MSGHANDLE_PP_SEQ_ELEM_226
# define MSGHANDLE_PP_SEQ_ELEM_228(_) MSGHANDLE_PP_SEQ_ELEM_227
# define MSGHANDLE_PP_SEQ_ELEM_229(_) MSGHANDLE_PP_SEQ_ELEM_228
# define MSGHANDLE_PP_SEQ_ELEM_230(_) MSGHANDLE_PP_SEQ_ELEM_229
# define MSGHANDLE_PP_SEQ_ELEM_231(_) MSGHANDLE_PP_SEQ_ELEM_230
# define MSGHANDLE_PP_SEQ_ELEM_232(_) MSGHANDLE_PP_SEQ_ELEM_231
# define MSGHANDLE_PP_SEQ_ELEM_233(_) MSGHANDLE_PP_SEQ_ELEM_232
# define MSGHANDLE_PP_SEQ_ELEM_234(_) MSGHANDLE_PP_SEQ_ELEM_233
# define MSGHANDLE_PP_SEQ_ELEM_235(_) MSGHANDLE_PP_SEQ_ELEM_234
# define MSGHANDLE_PP_SEQ_ELEM_236(_) MSGHANDLE_PP_SEQ_ELEM_235
# define MSGHANDLE_PP_SEQ_ELEM_237(_) MSGHANDLE_PP_SEQ_ELEM_236
# define MSGHANDLE_PP_SEQ_ELEM_238(_) MSGHANDLE_PP_SEQ_ELEM_237
# define MSGHANDLE_PP_SEQ_ELEM_239(_) MSGHANDLE_PP_SEQ_ELEM_238
# define MSGHANDLE_PP_SEQ_ELEM_240(_) MSGHANDLE_PP_SEQ_ELEM_239
# define MSGHANDLE_PP_SEQ_ELEM_241(_) MSGHANDLE_PP_SEQ_ELEM_240
# define MSGHANDLE_PP_SEQ_ELEM_242(_) MSGHANDLE_PP_SEQ_ELEM_241
# define MSGHANDLE_PP_SEQ_ELEM_243(_) MSGHANDLE_PP_SEQ_ELEM_242
# define MSGHANDLE_PP_SEQ_ELEM_244(_) MSGHANDLE_PP_SEQ_ELEM_243
# define MSGHANDLE_PP_SEQ_ELEM_245(_) MSGHANDLE_PP_SEQ_ELEM_244
# define MSGHANDLE_PP_SEQ_ELEM_246(_) MSGHANDLE_PP_SEQ_ELEM_245
# define MSGHANDLE_PP_SEQ_ELEM_247(_) MSGHANDLE_PP_SEQ_ELEM_246
# define MSGHANDLE_PP_SEQ_ELEM_248(_) MSGHANDLE_PP_SEQ_ELEM_247
# define MSGHANDLE_PP_SEQ_ELEM_249(_) MSGHANDLE_PP_SEQ_ELEM_248
# define MSGHANDLE_PP_SEQ_ELEM_250(_) MSGHANDLE_PP_SEQ_ELEM_249
# define MSGHANDLE_PP_SEQ_ELEM_251(_) MSGHANDLE_PP_SEQ_ELEM_250
# define MSGHANDLE_PP_SEQ_ELEM_252(_) MSGHANDLE_PP_SEQ_ELEM_251
# define MSGHANDLE_PP_SEQ_ELEM_253(_) MSGHANDLE_PP_SEQ_ELEM_252
# define MSGHANDLE_PP_SEQ_ELEM_254(_) MSGHANDLE_PP_SEQ_ELEM_253
# define MSGHANDLE_PP_SEQ_ELEM_255(_) MSGHANDLE_PP_SEQ_ELEM_254
#
# endif
