{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerServiceInterface/SoftwareManagerServiceInterface/GetSpecificVersionInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VersionItem",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/VersionItem"
    },
    {
      "Name": "Response",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/Response"
    }
  ],
  "IsPlane": "false"
}