{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/BusniessRemoteControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "steering_wheel",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t",
      "Padding": "4"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "accelerator",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "remotectrl_flag",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "estop_flag",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "steer_torque",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "eng_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool",
      "Padding": "3"
    },
    {
      "Name": "ctrl_level",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "tick",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "in_place",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}