{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/FmAlarmReceiveServiceInterface/FmReportAlmProcPolicyService/ReportAlmProcPolicyInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "UInt8",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "true"
}