{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/ExpectedVersionCheckResult",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "checkStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "expectedVersion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/SysVersion"
    },
    {
      "Name": "currVersion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/SysVersion"
    }
  ],
  "IsPlane": "false"
}