{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/SingleStateField",
  "Namespace": "::ara::sm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "functionGroupName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "stateName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "processResult",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    }
  ],
  "IsPlane": "false"
}