{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DisplayMsgDataType/RotateModeE",
  "Namespace": "::ara::display",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
  "value": [
    {
      "Label": "DO_NOT_ROTATE",
      "Value": "0"
    },
    {
      "Label": "ROTATE_MODE_90_CLOCKWISE",
      "Value": "1"
    },
    {
      "Label": "ROTATE_MODE_180_CLOCKWISE",
      "Value": "2"
    },
    {
      "Label": "ROTATE_MODE_270_CLOCKWISE",
      "Value": "3"
    }
  ]
}