{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerServiceInterface/SoftwareManagerServiceInterface/CleanWorkDirInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "WhiteList",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/WhiteList"
    }
  ],
  "IsPlane": "false"
}