{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/PerceptionSemanticObj",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "xg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "yg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "obj_size",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/PerceptionLWH"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "cells",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/PerceptionSemanticCellVec"
    },
    {
      "Name": "plan_risk_level",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "rect_2d",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafRect2D"
    }
  ],
  "IsPlane": "false"
}