{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VideoReceiverReport",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ts",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int64_t"
    },
    {
      "Name": "fps",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "bps",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "total_latency",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    }
  ],
  "IsPlane": "true"
}