{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/CommonFaultInfo",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "info",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "error_code",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "false"
}