{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerServiceInterface/SoftwareManagerServiceInterface/GetVersionInfoOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "SysVersion",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/SysVersion"
    },
    {
      "Name": "Response",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/Response"
    }
  ],
  "IsPlane": "false"
}