{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/GetHistoryType",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "Time",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "Name",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/SwNameType"
    },
    {
      "Name": "Version",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/StrongRevisionLabelString"
    },
    {
      "Name": "Action",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/ActionType"
    },
    {
      "Name": "Resolution",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/ResultType"
    }
  ],
  "IsPlane": "false"
}