{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafWheelSpeedList",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader"
    },
    {
      "Name": "wheel_speed_vec",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafWheelSpeedVec"
    }
  ],
  "IsPlane": "false"
}