{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/ComponentHistoryRecordType",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "startTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "endTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "devName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "pkgName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "oldVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "newVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "actionType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "errorCode",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "status",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "message",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}