{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/CommonTimeChain",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "t1",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "t2",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "from_module",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "to_module",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}