{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "timestamp",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafTime"
    },
    {
      "Name": "frameID",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "time_chain_vec",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonTimeChainVec"
    }
  ],
  "IsPlane": "false"
}