{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrajetoryPredictionMsgDataType/PathPoint",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "point",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "s",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "theta",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "kappa",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "dkappa",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "ddkappa",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "true"
}