{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrafficLightMsgDataType/TrafficLightArray",
  "Namespace": "::ara::trafficlight",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/FunctionalSoftware/TrafficLightMsgDataType/TrafficLightHeader"
    },
    {
      "Name": "object_list",
      "Type": "/HuaweiMDC/FunctionalSoftware/TrafficLightMsgDataType/TrafficLightVector"
    },
    {
      "Name": "count",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "is_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    }
  ],
  "IsPlane": "false"
}