{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/BusinessPoint",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "index",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t",
      "Padding": "4"
    },
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "xg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "yg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "direction",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}