{
  "ShortName": "/HuaweiMDC/Sotif/PerceptionSafetyArrayMsgDataType/PerceptionSafety",
  "Namespace": "::sotif",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeStampFirst",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonTime"
    },
    {
      "Name": "eventId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "sensorId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "eventLevel",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "actionName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "para",
      "Type": "/HuaweiMDC/ApplicationDataType/FloatArray"
    },
    {
      "Name": "timeStampLast",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonTime"
    }
  ],
  "IsPlane": "false"
}