{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/TaskExecuteStatus",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "current_limit_speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "task_points",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/BusinessTaskPoints"
    },
    {
      "Name": "distance_to_nearest",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "total_mileage",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "current_mileage",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "progress",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    }
  ],
  "IsPlane": "false"
}