{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SammSceneMsgDataType/SammScene",
  "Namespace": "::ara::samm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "scene",
      "Type": "/HuaweiMDC/FunctionalSoftware/SammSceneMsgDataType/Scene"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/Header"
    }
  ],
  "IsPlane": "false"
}