{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/ResetRequestType",
  "Namespace": "",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppBasicDataType/uint32_t",
  "value": [
    {
      "Label": "kSoftReset",
      "Value": "0"
    },
    {
      "Label": "kHardReset",
      "Value": "1"
    },
    {
      "Label": "kKeyOffOnReset",
      "Value": "2"
    },
    {
      "Label": "kCustomReset",
      "Value": "3"
    }
  ]
}