{
  "ShortName": "/HuaweiMDC/ApplicationDataType/VirtualWall",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "target_speed",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "target_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "desire_follow_seconds",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    }
  ],
  "IsPlane": "true"
}