{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrajPredictMsgDataType/TrajPoint",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pathPoint",
      "Type": "/HuaweiMDC/FunctionalSoftware/TrajPredictMsgDataType/PathPoint"
    },
    {
      "Name": "speed",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "acceleration",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "relativeTime",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "true"
}