{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleLatControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "target_angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "target_torque",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "centor_control_value",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int8_t",
      "Padding": "3"
    },
    {
      "Name": "target_curvature",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "steer_control_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "true"
}