{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrafficSignalMsgDataType/TrafficSignal",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "color",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rect3d",
      "Type": "/HuaweiMDC/ApplicationDataType/Rect3d"
    },
    {
      "Name": "laneId",
      "Type": "/HuaweiMDC/ApplicationDataType/Int32Array"
    },
    {
      "Name": "position",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "distance",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "flash",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "timeTrack",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "timeFlash",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "timeV2X",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "timeCreation",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonTime"
    }
  ],
  "IsPlane": "false"
}