{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmFaultFull",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "faultObj",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "phyCpuNo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cpuCoreNo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "clss",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "level",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "flag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "componentId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "count",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "timeFirst",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "timeLast",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "para",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "desc",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "actionName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "actionResult",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "subFaultVec",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmStringVec"
    }
  ],
  "IsPlane": "false"
}