{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/BusinessTaskPoint",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "high",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "pitch",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "yaw",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "zoom",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "lat",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "lon",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "dir",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "task_time",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    }
  ],
  "IsPlane": "false"
}