{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SceneFeatureMsgDataType/SceneFeature",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "defaultFeatures",
      "Type": "/HuaweiMDC/FunctionalSoftware/SceneFeatureMsgDataType/FeatureVector"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "customFeatures",
      "Type": "/HuaweiMDC/FunctionalSoftware/SceneFeatureMsgDataType/FeatureVector"
    }
  ],
  "IsPlane": "false"
}