{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SelectPointMsgDataType/SelectPoint",
  "Namespace": "::ara::selectpoint",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/FunctionalSoftware/SelectPointMsgDataType/Header"
    },
    {
      "Name": "point",
      "Type": "/HuaweiMDC/FunctionalSoftware/SelectPointMsgDataType/Point"
    }
  ],
  "IsPlane": "false"
}