{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafRect2D",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "center",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2D"
    },
    {
      "Name": "location",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2D"
    },
    {
      "Name": "centerCovariance",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2D"
    },
    {
      "Name": "size",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2D"
    },
    {
      "Name": "sizeCovariance",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2D"
    },
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "orientationCovariance",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "corners",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2DVec"
    }
  ],
  "IsPlane": "false"
}