{
  "ShortName": "/HuaweiMDC/CommonDataTypes/IdpAppRemoteControlInAP",
  "Namespace": "::ara::common",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "steering_wheel_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "gear_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "brake_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "accelerator_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "remotectrl_flag_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "estop_flag_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "steer_torque_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "eng_status_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "ctrl_level_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "in_place_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "tick_ap",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "true"
}