{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/CommonSensorCalibration",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "prerotaxis_0",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "prerotaxis_1",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "prerotaxis_2",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "prerotdegree_0",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "prerotdegree_1",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "prerotdegree_2",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "xoffset",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "yoffset",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "zoffset",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "roll",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "pitch",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "yaw",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "z_ground_offset",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    }
  ],
  "IsPlane": "false"
}