{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerServiceInterface/UpdateManagerServiceInterface/ActivateByModeInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "SwNameVectorType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/SwNameVectorType"
    },
    {
      "Name": "SwNameVectorType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/SwNameVectorType"
    },
    {
      "Name": "Int8",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    }
  ],
  "IsPlane": "false"
}