{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/SensorRadarPoint4D",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "motionStatus",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "azimuth",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "elevation",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "range",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "range_rate",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "rangeStdDev",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "rangeRateStdDev",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "azimuthStdDev",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "elevationStdDev",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "existStatus",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "falseAlarmProb",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "heightConfidence",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "snr",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "attribState",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "ambg_state",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "modeFlag",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "vx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "vy",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "vz",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    }
  ],
  "IsPlane": "true"
}