{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagComClient/SendResponseInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "UInt64",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "Boolean",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "ByteVector",
      "Type": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/ByteVector"
    }
  ],
  "IsPlane": "false"
}