{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Quaternion",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "w",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}