{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrafficLightMsgDataType/TrafficLight",
  "Namespace": "::ara::trafficlight",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "confidence",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "objectID",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "color",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "box_image",
      "Type": "/HuaweiMDC/ApplicationDataType/Rect"
    },
    {
      "Name": "lanes_id",
      "Type": "/HuaweiMDC/ApplicationDataType/Int32Array"
    },
    {
      "Name": "position",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "distance",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "flash",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "time_track",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "time_flash",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "time_v2x",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "time_creation",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "false"
}