{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleLonControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "target_speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "target_torque",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "target_pressure",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "actuator_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "emergency_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "handbrake",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "shift_position",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "control_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}