{
  "ShortName": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/RoadPiece",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "roadPiece",
      "Type": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/LaneSeriesVector"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "roadType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}