{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/FusionObjectArrayMsgDataType/FusionObjectArray",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "object",
      "Type": "/HuaweiMDC/FunctionalSoftware/FusionObjectArrayMsgDataType/FusionObjectVector"
    }
  ],
  "IsPlane": "false"
}