{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppImage",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "encoding",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "step",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/IdpUint8Vec"
    }
  ],
  "IsPlane": "false"
}