{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/PerceptionTerrainPatch",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "patch_center",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3f"
    },
    {
      "Name": "slopx",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "slopy",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "terrain_height",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}