{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/ResetCode",
  "Namespace": "::ara::sm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "resetType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/ResetType",
      "Padding": "3"
    },
    {
      "Name": "resetTime",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}