{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SmcServiceInterface/TriggerInOut/ResetSystemInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "ResetCode",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/ResetCode"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "ResetCause",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/ResetCause"
    }
  ],
  "IsPlane": "false"
}