{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/FmAlarmReceiveServiceInterface/FmReportAlmProcPolicyService/DisableOneAlarmInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "UInt16",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "UInt16",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "UInt16",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    }
  ],
  "IsPlane": "true"
}