{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppVideoEditorParameter",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "output_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "remote_control_alarm",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "remote_control_assist",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "front_source",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "split_adaptive",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "video_left_",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "video_main_",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "video_right_",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "objects",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafFusionOutArray"
    },
    {
      "Name": "remote_control",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafEgoTrajectory"
    },
    {
      "Name": "path",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafEgoTrajectory"
    },
    {
      "Name": "target_points",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3DVec"
    },
    {
      "Name": "video_third_person",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "target_point",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D"
    },
    {
      "Name": "split_parames_",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppVideoSplitParamVec"
    }
  ],
  "IsPlane": "false"
}