{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DisplayMsgDataType/ImageFormatTypeE",
  "Namespace": "::ara::display",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
  "value": [
    {
      "Label": "IMAGE_FORMAT_RGB888",
      "Value": "0"
    },
    {
      "Label": "IMAGE_FORMAT_YUV420_NV12",
      "Value": "1"
    },
    {
      "Label": "IMAGE_FORMAT_YUV420_NV21",
      "Value": "2"
    }
  ]
}