{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/LaneLineArrayMsgDataType/LaneLineFitParam",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "a",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "b",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "c",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "d",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "true"
}