{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppGlobalPatrolControlParameter",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "command",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "file_track",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "file_map",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "file_task",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "dest",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "roads_info",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "is_loop",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    }
  ],
  "IsPlane": "false"
}