{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/ActionType",
  "Namespace": "::mdc::swm",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kUpdate",
      "Value": "0"
    },
    {
      "Label": "kInstall",
      "Value": "1"
    },
    {
      "Label": "kRemove",
      "Value": "2"
    }
  ]
}