{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmFaultData",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "faultObj",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "phyCpuNo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "cpuCoreNo",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "componentId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "flag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "paraNum",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "para",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmParaArray"
    },
    {
      "Name": "clss",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "time",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmCharVec"
    }
  ],
  "IsPlane": "false"
}