{
  "ShortName": "/HuaweiMDC/Sotif/PerceptionSafetyArrayMsgDataType/PerceptionSafetyArray",
  "Namespace": "::sotif",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "result",
      "Type": "/HuaweiMDC/Sotif/PerceptionSafetyArrayMsgDataType/PerceptionSafetyVector"
    }
  ],
  "IsPlane": "false"
}