{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/LaneLineArrayMsgDataType/LaneLineArray",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/FunctionalSoftware/LaneLineArrayMsgDataType/LaneHeader"
    },
    {
      "Name": "package_type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "lane_list",
      "Type": "/HuaweiMDC/FunctionalSoftware/LaneLineArrayMsgDataType/LaneLineVector"
    }
  ],
  "IsPlane": "false"
}