{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/VersionItem",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "location",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    },
    {
      "Name": "versions",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/VersionInfoVector"
    },
    {
      "Name": "deviceStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}