{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/VerifyCheckResult",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "pkgName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "deviceName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "currentVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "expectVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "message",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}