{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/PlanningResultMsgDataType/WayPoint",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "theta",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "curvature",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "s",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "deltaCurvature",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "deltaX",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "deltaY",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "laneId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}