{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/FaultInfo",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "code",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "handle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "desc",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "extra_desc",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "timestamp",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "from",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}