{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/SammFeature",
  "Namespace": "::ara::samm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "defaultFeatures",
      "Type": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/DefaultFeatureVector"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/FunctionalSoftware/SelectPointMsgDataType/Header"
    },
    {
      "Name": "customFeatures",
      "Type": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/CustomFeatureVector"
    }
  ],
  "IsPlane": "false"
}