{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Rect3d",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "center",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "centerCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "size",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "sizeCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "orientationCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    },
    {
      "Name": "corners",
      "Type": "/HuaweiMDC/ApplicationDataType/PointArray"
    }
  ],
  "IsPlane": "false"
}