{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppVision4CamsDataInType",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "image_front_h30_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_front_h30",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_front_h60_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_front_h60",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_left_h90_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_left_h90",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_right_h90_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_right_h90",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_pano_left_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_pano_left",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_pano_right_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_pano_right",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    },
    {
      "Name": "image_pano_back_valid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "image_pano_back",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppImage"
    }
  ],
  "IsPlane": "false"
}