{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/ProcessSwPackageReturnType",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "result",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "transferId",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/TransferIdType"
    }
  ],
  "IsPlane": "false"
}