{
  "ShortName": "/HuaweiMDC/ApplicationDataType/PathWithCovariance",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "poses",
      "Type": "/HuaweiMDC/ApplicationDataType/PoseWithCovarianceStamped"
    },
    {
      "Name": "time_window",
      "Type": "/HuaweiMDC/ApplicationDataType/TimeWindow"
    }
  ],
  "IsPlane": "false"
}