{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafTwistWithCovariance",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "twist",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafTwist"
    },
    {
      "Name": "covariance",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/IdpDoubleVec"
    }
  ],
  "IsPlane": "false"
}