{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrafficSignalMsgDataType/TrafficSignalArray",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "tlObject",
      "Type": "/HuaweiMDC/FunctionalSoftware/TrafficSignalMsgDataType/TrafficSignalVector"
    }
  ],
  "IsPlane": "false"
}