{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/AnswerMsgType",
  "Namespace": "::mdc::ex_wdg",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "versionId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "msgId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "answerParamLen",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "qaParam",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/ParamType"
    }
  ],
  "IsPlane": "false"
}