{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/PreCheckResult",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "result",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "results",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/CheckItemResultVector"
    }
  ],
  "IsPlane": "false"
}