{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Lane",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "speed_limit",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "left_changable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "left_changable_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "right_changable_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "right_changable",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "road_points",
      "Type": "/HuaweiMDC/ApplicationDataType/Pose2DArray"
    },
    {
      "Name": "left_edge",
      "Type": "/HuaweiMDC/ApplicationDataType/Pose2DArray"
    },
    {
      "Name": "right_edge",
      "Type": "/HuaweiMDC/ApplicationDataType/Pose2DArray"
    },
    {
      "Name": "next_lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "previous_lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "left_lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "right_lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "traffic_light_state",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "traffic_light_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "stop_sign_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "parking_pole_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "cross_walk_distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "sub_lanes",
      "Type": "/HuaweiMDC/ApplicationDataType/SubLaneArray"
    }
  ],
  "IsPlane": "false"
}