{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/SoftwareVersionItem",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "deviceName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "swName",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "version",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}