{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleSensorState",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VCU_fault",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "vehicle_total_mile",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "vehicle_ready_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "offroad_working_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "parking_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "motor_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "power_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "speed_limit",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "power_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "low_beam_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "far_beam_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "turn_left_light_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "turn_right_light_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "lidar_power_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "radar_power_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "night_camera_power_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "horn_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "1"
    },
    {
      "Name": "fuel_level",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "remaining_mileage",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "bms_battery_soc",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "voltage",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    }
  ],
  "IsPlane": "true"
}