{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/CanCheckList",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "idNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "controlMethod",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "canIdInfos",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/CanIdInfoList"
    }
  ],
  "IsPlane": "false"
}