{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/GidStatusStruct",
  "Namespace": "::ara::diag",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "GID",
      "Type": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/ByteArray"
    },
    {
      "Name": "furtherActionReq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "syncStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    }
  ],
  "IsPlane": "false"
}