{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/RoutineErrorCode",
  "Namespace": "",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kERoutineNoError",
      "Value": "0"
    },
    {
      "Label": "kERoutineUndefined",
      "Value": "1"
    },
    {
      "Label": "kERoutineNotFound",
      "Value": "2"
    },
    {
      "Label": "kERoutineRequestInvalid",
      "Value": "3"
    },
    {
      "Label": "kERoutineInternalError",
      "Value": "4"
    },
    {
      "Label": "kERoutineHandlerNotAvailable",
      "Value": "5"
    },
    {
      "Label": "kERoutineSequenceError",
      "Value": "6"
    },
    {
      "Label": "kERoutineRequestOutofRange",
      "Value": "7"
    }
  ]
}