{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/PackClientType/PackageDigestType",
  "Namespace": "::mdc::dcap",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "digestStr",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "retCode",
      "Type": "/HuaweiMDC/StdCppDataType/Int32",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}