{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafRect3D",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "center",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D"
    },
    {
      "Name": "centerCovariance",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D"
    },
    {
      "Name": "size",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D"
    },
    {
      "Name": "sizeCovariance",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D"
    },
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "orientationCovariance",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "corners",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3DVec"
    }
  ],
  "IsPlane": "false"
}