{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/SwClusterStateType",
  "Namespace": "::mdc::swm",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kPresent",
      "Value": "0"
    },
    {
      "Label": "kAdded",
      "Value": "1"
    },
    {
      "Label": "kUpdated",
      "Value": "2"
    },
    {
      "Label": "kRemoved",
      "Value": "3"
    }
  ]
}