{
  "ShortName": "/HuaweiMDC/ApplicationDataType/RoadPoint",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "theta",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "curvature",
      "Type": "/HuaweiMDC/StdCppDataType/Float",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}