{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Rect",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    }
  ],
  "IsPlane": "true"
}