{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/PackageManagerStatusType",
  "Namespace": "::mdc::swm",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kIdle",
      "Value": "0"
    },
    {
      "Label": "kReady",
      "Value": "1"
    },
    {
      "Label": "kBusy",
      "Value": "2"
    },
    {
      "Label": "kActivating",
      "Value": "3"
    },
    {
      "Label": "kActivated",
      "Value": "4"
    },
    {
      "Label": "kRollingBack",
      "Value": "5"
    },
    {
      "Label": "kRolledBack",
      "Value": "6"
    },
    {
      "Label": "kCleaning_Up",
      "Value": "7"
    },
    {
      "Label": "kVerifying",
      "Value": "8"
    }
  ]
}