{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigServiceInterface/VoConfigServiceInterface/SetVoChnAttrInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "ChnAttr",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/ChnAttr"
    }
  ],
  "IsPlane": "true"
}