{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigServiceInterface/VoConfigServiceInterface/GetVoSourceOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VoEnum",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/VoEnum",
      "Padding": "3"
    },
    {
      "Name": "int32_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "true"
}