{
  "ShortName": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/LanePiece",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "startS",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "endS",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "false"
}