{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/PlanningResultMsgDataType/Estop",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "isStop",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "description",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    }
  ],
  "IsPlane": "false"
}