{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/BusinessCommandParameter",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "patrol_name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "patrol_dest",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "patrol_type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "patrol_loop",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "patrol_roads",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "max_speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "task_avoid_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "command",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "follow_min_dis",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "follow_thw",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "follow_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "follow_x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "follow_y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "view_width",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "view_height",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "return_lat",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "return_lon",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "fence",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "pose",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafPose"
    }
  ],
  "IsPlane": "false"
}