{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgCameraDetectionResult",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader"
    },
    {
      "Name": "image_objects",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHaf3dDetectionOutArray"
    },
    {
      "Name": "image_segmentation_vec",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgImageDataVec"
    }
  ],
  "IsPlane": "false"
}