{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafEstop",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader"
    },
    {
      "Name": "isEstop",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "description",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}