{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/FmServiceInterface/FmTransMcuDataService/ReportMcuDataInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "FmMcuDataHeader",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmMcuDataHeader"
    },
    {
      "Name": "Uint8Vector",
      "Type": "/HuaweiMDC/ApplicationDataType/Uint8Vector"
    }
  ],
  "IsPlane": "false"
}