{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleActState",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "throttle_info",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "steer_angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "steer_curvature",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "acceleration",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "shift_position",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "aeb_active",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "parking_mode_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "epb_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "drive_mode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "steering_mode_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "2"
    }
  ],
  "IsPlane": "true"
}