{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/FunctionGroupInfo",
  "Namespace": "::ara::sm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "functionGroupName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "stateNames",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/StateNames"
    }
  ],
  "IsPlane": "false"
}