{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SceneMsgDataType/SceneDag",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "tasks",
      "Type": "/HuaweiMDC/FunctionalSoftware/SceneMsgDataType/TaskVector"
    },
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}