{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppRemoteControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "steering_wheel",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "accelerator",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "remotectrl_flag",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "estop_flag",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "steer_torque",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "eng_status",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "ctrl_level",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "in_place",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool"
    },
    {
      "Name": "tick",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "speed_limit",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "set_speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "security_assist_enabled",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "false"
}