{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/Feature",
  "Namespace": "::ara::samm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "description",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}