{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/CheckItemResult",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "result",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "message",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}