{
  "ShortName": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/NaviRoadPoint",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "s",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "pose",
      "Type": "/HuaweiMDC/ApplicationDataType/Point"
    }
  ],
  "IsPlane": "false"
}