{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/Object2dArrayMsgDataType/Object2d",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "existProb",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "timeCreation",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonTime"
    },
    {
      "Name": "cls",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "clsDescription",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "clsConfidence",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "velocity",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "absVelocity",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "cipvFlag",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "acceleration",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "cameraStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "coordinate",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "blinkerStatus",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "rect2d",
      "Type": "/HuaweiMDC/ApplicationDataType/Rect2d"
    }
  ],
  "IsPlane": "false"
}