{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/PerceptionUtraData",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "trigger_stamp",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "id",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "dis",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "cells",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint2DVec"
    }
  ],
  "IsPlane": "false"
}