{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/AlarmInfo",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "alarmId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "alarmObj",
      "Type": "/HuaweiMDC/StdCppDataType/UInt16"
    },
    {
      "Name": "clss",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "level",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "status",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "time",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "desc",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}