{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/TrackPoint",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lon",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "lat",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "index",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t",
      "Padding": "4"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "direction",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int8_t",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}