{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmFaultDetail",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultData",
      "Type": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmFaultData"
    },
    {
      "Name": "actionName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "timePointFirst",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "timePointLast",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    }
  ],
  "IsPlane": "false"
}