{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppStatus",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "record_status_track",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppStatusMessage"
    },
    {
      "Name": "record_status_fence",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppStatusMessage"
    },
    {
      "Name": "record_status_map",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppStatusMessage"
    }
  ],
  "IsPlane": "false"
}