{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Rect2d",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "center",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "centerCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "size",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "sizeCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "orientationCovariance",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "corners",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    },
    {
      "Name": "leftTop",
      "Type": "/HuaweiMDC/ApplicationDataType/PointxyDouble"
    }
  ],
  "IsPlane": "true"
}