{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/CanCtrlConfig",
  "Namespace": "::mdc::devm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "channelId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "upStream",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/CanCheckList"
    },
    {
      "Name": "downStream",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DevmCenterMsgDataType/DataTypes/CanCheckList"
    }
  ],
  "IsPlane": "false"
}