{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmMcuDataRetInfo",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "type",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "seqId",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "retCode",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    }
  ],
  "IsPlane": "true"
}