{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/AnswerEnum",
  "Namespace": "::mdc::ex_wdg",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "ANSWER_OPENING",
      "Value": "0"
    },
    {
      "Label": "ANSWER_PANDA",
      "Value": "1"
    },
    {
      "Label": "ANSWER_GLODEN_MONKEY",
      "Value": "2"
    },
    {
      "Label": "ANSWER_SOUTH_CHINA_TIGER",
      "Value": "3"
    },
    {
      "Label": "ANSWER_CRESTED_IBIS",
      "Value": "4"
    },
    {
      "Label": "ANSWER_CHINESE_STURGEON",
      "Value": "5"
    },
    {
      "Label": "ANSWER_CHINESE_RURAL_DOG",
      "Value": "6"
    }
  ]
}