{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleActControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "lat_control",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/VehicleLatControl"
    },
    {
      "Name": "lon_control",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/VehicleLonControl"
    },
    {
      "Name": "sensor_control",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/VehicleSensorControl"
    }
  ],
  "IsPlane": "false"
}