{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/VehicleInformation",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "vehicle_sensor_state",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/VehicleSensorState"
    },
    {
      "Name": "vehicle_act_state",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/VehicleActState"
    },
    {
      "Name": "wheel_speed",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafWheelSpeedList"
    }
  ],
  "IsPlane": "false"
}