{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafWheelSpeed",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "wheelDirection",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "3"
    },
    {
      "Name": "wheelCount",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "wheelSpeedMps",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "wheelCountValid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "wheelSpeedMpsValid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "wheelSpeedPos",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t",
      "Padding": "1"
    }
  ],
  "IsPlane": "true"
}