{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgPointXYZIRT",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "intensity",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint16_t"
    },
    {
      "Name": "ring",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint16_t"
    },
    {
      "Name": "latency",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    }
  ],
  "IsPlane": "true"
}