{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafWayPoint",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader"
    },
    {
      "Name": "xg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "yg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "zg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "angle",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "theta",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "curvature",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "s",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "deltaCurvature",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "laneId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "deltaX",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "deltaY",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    }
  ],
  "IsPlane": "false"
}