{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/SysVersion",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sysVersion",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "state",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    },
    {
      "Name": "itemVersions",
      "Type": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/VersionItemVector"
    }
  ],
  "IsPlane": "false"
}