{
  "ShortName": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/LaneSeries",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "laneSeries",
      "Type": "/HuaweiMDC/ApplicationComplexDataType/NavigationDataType/LanePieceVector"
    },
    {
      "Name": "isDrivable",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "directionType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "false"
}