{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppVideoParameter",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "editor_parameter",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppVideoEditorParameter"
    },
    {
      "Name": "encoding_parameter",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppVideoEncodingParameter"
    }
  ],
  "IsPlane": "false"
}