{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SelectPointMsgDataType/Point",
  "Namespace": "::ara::selectpoint",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    }
  ],
  "IsPlane": "true"
}