{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/PerceptionSemanticCell",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "xg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "yg",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "dh",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}