{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrafficLightMsgDataType/TrafficLightHeader",
  "Namespace": "::ara::trafficlight",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/FunctionalSoftware/ObjectArrayMsgDataType/Time"
    },
    {
      "Name": "frameId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "count",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "false"
}