{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgCameraVPResult",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgHafHeader"
    },
    {
      "Name": "vp_result_vec",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/MsgCameraDetectionResultVec"
    }
  ],
  "IsPlane": "false"
}