{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgHafRadarTrackOrient",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "orientation",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "rms",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "quality",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    }
  ],
  "IsPlane": "true"
}