{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/PerceptionLWH",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "width",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    }
  ],
  "IsPlane": "true"
}