{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgTimeStampInfo",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeStampStatus",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint16_t",
      "Padding": "6"
    },
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int64_t"
    },
    {
      "Name": "autoSarTimeStamp",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int64_t"
    }
  ],
  "IsPlane": "true"
}