{
  "ShortName": "/HuaweiMDC/ApplicationDataType/SubLane",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    },
    {
      "Name": "priority",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "Padding": "3"
    },
    {
      "Name": "cross_point",
      "Type": "/HuaweiMDC/ApplicationDataType/Pose2D"
    },
    {
      "Name": "stop_point",
      "Type": "/HuaweiMDC/ApplicationDataType/Pose2D"
    }
  ],
  "IsPlane": "true"
}