{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SammSceneMsgDataType/ScenenDag",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sceneId",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "tasks",
      "Type": "/HuaweiMDC/FunctionalSoftware/SammSceneMsgDataType/TaskVector"
    },
    {
      "Name": "sceneName",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}