{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SmcMsgDataTypes/DataTypes/StateTransitionResult",
  "Namespace": "::ara::sm",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kSuccess",
      "Value": "0"
    },
    {
      "Label": "kInvalid",
      "Value": "1"
    },
    {
      "Label": "kFailed",
      "Value": "2"
    },
    {
      "Label": "kTimeout",
      "Value": "3"
    },
    {
      "Label": "kCommError",
      "Value": "4"
    },
    {
      "Label": "kFileError",
      "Value": "5"
    },
    {
      "Label": "kRejected",
      "Value": "6"
    }
  ]
}