{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/MonitorActionType",
  "Namespace": "",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kPassed",
      "Value": "0"
    },
    {
      "Label": "kFailed",
      "Value": "1"
    },
    {
      "Label": "kPrepassed",
      "Value": "2"
    },
    {
      "Label": "kPrefailed",
      "Value": "3"
    },
    {
      "Label": "kFdcThresholdReached",
      "Value": "4"
    },
    {
      "Label": "kResetTestFailed",
      "Value": "5"
    },
    {
      "Label": "kFreezeDebouncing",
      "Value": "6"
    },
    {
      "Label": "kResetDebouncing",
      "Value": "7"
    },
    {
      "Label": "kPrestore",
      "Value": "8"
    },
    {
      "Label": "kClearPrestore",
      "Value": "9"
    }
  ]
}