{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/VideoParam",
  "Namespace": "::mdc::vo",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "imageFormat",
      "Type": "/HuaweiMDC/PlatformServiceInterface/DisplayMsgDataType/ImageFormatTypeE",
      "Padding": "3"
    },
    {
      "Name": "frameRate",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint32_t"
    },
    {
      "Name": "resolution",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/Resolution"
    }
  ],
  "IsPlane": "true"
}