{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerServiceInterface/UpdateManagerServiceInterface/GetVerifyListOutput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "VerifyCheckResultVectorType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/UpdateManagerMsgDataTypes/DataTypes/VerifyCheckResultVectorType"
    },
    {
      "Name": "Boolean",
      "Type": "/HuaweiMDC/StdCppDataType/Boolean"
    },
    {
      "Name": "Int8",
      "Type": "/HuaweiMDC/StdCppDataType/Int8"
    }
  ],
  "IsPlane": "false"
}