{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/SensorRadarPointCloud",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "objs",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/SensorRadarPoint4DVec"
    }
  ],
  "IsPlane": "false"
}