{
  "ShortName": "/HuaweiMDC/MdcPlatformServices/PlatformServiceInterface/DataTypes/FmFaultStatData",
  "Namespace": "::mdc::fm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "faultCnt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "faultClearCnt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "minTimeInvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "maxTimeInvl",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "avgTimeInvl",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "alarmCnt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    },
    {
      "Name": "alarmClearCnt",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}