{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/TimeDelayDataType",
  "Namespace": "::ara::timedelay",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/Header"
    },
    {
      "Name": "mdcRecvTimePoint",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/TimePoint"
    },
    {
      "Name": "sensorAccessRecvTimePoint",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/TimePoint"
    },
    {
      "Name": "publishTimePoint",
      "Type": "/HuaweiMDC/PlatformServiceInterface/TimeDelayDataType/TimePoint"
    },
    {
      "Name": "driverTimeDelay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "sensorAccessTimeDelay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "forwardTimeDelay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "frameTimeDelay",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    }
  ],
  "IsPlane": "false"
}