{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppSoftControl",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "low_beam_ctrl",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "max_speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/float"
    },
    {
      "Name": "other_ctrl",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    },
    {
      "Name": "record_return_path",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "true"
}