{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/PlatformStateAgentServiceInterface/PlatformStateAgent/RequestPlatformStateInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "Uint32Vector",
      "Type": "/HuaweiMDC/ApplicationDataType/Uint32Vector"
    }
  ],
  "IsPlane": "false"
}