{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppPatrolDynamicParameter",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "avoid",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t",
      "Padding": "4"
    },
    {
      "Name": "speed",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "paused",
      "Type": "/HuaweiMDC/StdCppBasicDataType/bool",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}