{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/ObjectArrayMsgDataType/ObjectArray",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/CommonDataTypes/CommonHeader"
    },
    {
      "Name": "package_type",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "object_list",
      "Type": "/HuaweiMDC/FunctionalSoftware/ObjectArrayMsgDataType/ObjectVector"
    }
  ],
  "IsPlane": "false"
}