{
  "ShortName": "/HuaweiMDC/DiagDataType/RequestTriggerType",
  "Namespace": "::ara::diag",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "instanceSpecifier",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "serailNumber",
      "Type": "/HuaweiMDC/StdCppDataType/UInt64"
    },
    {
      "Name": "eventType",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}