{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/PackClientType/PackParamType",
  "Namespace": "::mdc::dcap",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "startTimestamp",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "endTimestamp",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    },
    {
      "Name": "fileType",
      "Type": "/HuaweiMDC/PlatformServiceInterface/PackClientType/ObjectMap",
      "IsOptional": "false"
    },
    {
      "Name": "packageSize",
      "Type": "/HuaweiMDC/StdCppDataType/UInt32",
      "IsOptional": "false"
    },
    {
      "Name": "path",
      "Type": "/HuaweiMDC/StdCppDataType/String",
      "IsOptional": "false"
    }
  ],
  "IsPlane": "false"
}