{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/AppVideoSplitParam",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "channel_name",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "view_area_points",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppVideoSplitPoint"
    },
    {
      "Name": "crop_area_points",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/AppVideoSplitPoint"
    }
  ],
  "IsPlane": "false"
}