{
  "ShortName": "/HuaweiMDC/ApplicationDataType/Gap",
  "Namespace": "",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "speed_front",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "speed_back",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "distance",
      "Type": "/HuaweiMDC/StdCppDataType/Float"
    },
    {
      "Name": "lane_id",
      "Type": "/HuaweiMDC/StdCppDataType/Int32"
    }
  ],
  "IsPlane": "true"
}