{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/TrajPredictMsgDataType/TrajInPrediction",
  "Namespace": "::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "probability",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "trajectoryPoints",
      "Type": "/HuaweiMDC/FunctionalSoftware/TrajPredictMsgDataType/TrajPointVector"
    }
  ],
  "IsPlane": "false"
}