{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/FaultData",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/CommonHeader"
    },
    {
      "Name": "fault_info",
      "Type": "/HuaweiMDC/interface_manifests/datatypes/FaultInfoVec"
    },
    {
      "Name": "fault_level",
      "Type": "/HuaweiMDC/StdCppBasicDataType/int32_t"
    }
  ],
  "IsPlane": "false"
}