{
  "ShortName": "/HuaweiMDC/FunctionalSoftware/SammFeatureMsgDataType/Header",
  "Namespace": "::ara::samm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/StdCppDataType/Double"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/FunctionalSoftware/LocationMsgDataType/Time"
    },
    {
      "Name": "frameId",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}