{
  "ShortName": "/HuaweiMDC/interface_manifests/datatypes/MsgPoint3D",
  "Namespace": "::ara::adsfi",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/StdCppBasicDataType/double"
    }
  ],
  "IsPlane": "true"
}