{
  "ShortName": "/HuaweiMDC/PlatformServices/DiagMsgDataType/DataTypes/InitMonitorReasonType",
  "Namespace": "",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/StdCppDataType/UInt8",
  "value": [
    {
      "Label": "kClear",
      "Value": "0"
    },
    {
      "Label": "kRestart",
      "Value": "1"
    },
    {
      "Label": "kReenabled",
      "Value": "2"
    },
    {
      "Label": "kStorageEnabled",
      "Value": "3"
    }
  ]
}