{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerMsgDataTypes/DataTypes/VersionInfo",
  "Namespace": "::mdc::swm",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "partition",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "isRunning",
      "Type": "/HuaweiMDC/StdCppDataType/UInt8"
    },
    {
      "Name": "version",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}