{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/VoConfigServiceInterface/VoConfigServiceInterface/SetVoSourceInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "uint8_t",
      "Type": "/HuaweiMDC/StdCppBasicDataType/uint8_t"
    },
    {
      "Name": "VoEnum",
      "Type": "/HuaweiMDC/PlatformServiceInterface/VoConfigDataType/VoEnum"
    }
  ],
  "IsPlane": "true"
}