{
  "ShortName": "/HuaweiMDC/PlatformServiceInterface/SoftwareManagerServiceInterface/SoftwareManagerServiceInterface/GetSpecificVersionInfoInput",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    },
    {
      "Name": "String",
      "Type": "/HuaweiMDC/StdCppDataType/String"
    }
  ],
  "IsPlane": "false"
}